# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6da32548271820c8b546ea8066531dc6739f3f2f5fc06cf5da56b8d862bacace0a0e36962deb97b349a018571189557a1a12fa34f467eb4c63d755fce96bf8fc

test:
  secret_key_base: 6bc4a663e3d94298a662d505b05f459bb84895d9793e243dcd1643b55c5056a39689dade9526790cd22c38be9594fe21b128f5d0b02790885d5c5cd6f2280e04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
